version: '3'
services:
  api:
    env_file:
      - "app/.env"
    build:
      context: .
      dockerfile: Dockerfile
      #args:
    image: poptape/address/api:v0.1
    ports:
      - "1238:8011"
    restart: always
    volumes:
      - /var/log:/addresses/log
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"
    networks:
      - net_poptape
  db:
    #image: poptape/address/db:v0.1
    image: postgres:alpine
    restart: always
    env_file:
      - "app/.env"
#    environment:
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "1239:5432"
    volumes:
      - poptape_datavolume:/var/lib/postgresql/data
    networks:
      - net_poptape
networks:
  net_poptape:
    external: true
volumes:
  poptape_datavolume:
  
